name: Docqrex

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
              working-directory: ./docqrex
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm install --frozen-lockfile
            - name: Build website
              env:
                  BASE_URL: /docqrex/
              run: npm run build
              
            - name: Push to website branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: website
                  FOLDER: build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MESSAGE: 'Deploy website - based on {sha}'
